### ISSUE TITLE
No matching distribution for torch

### ISSUE THREAD

**Issue by philipperbd** [TUM-AAS/motron-cvpr22#1]
**To reproduce**
Create a virtual environment using conda.
Install every requirements using 'pip install -r requirements.txt'.

**Error:**
"No matching distribution found for torch==1.8.2+cu111".

**Comment by Tim-Salzmann** [comment]
Hi,

Thanks for reaching out. I assume torch >1.8 or even >2.0 should also work. Feel free to give it a try.

Best
Tim
